### PR TITLE
Added Basic Project files document setup

### PR DESCRIPTION
**Pull request by davidobi**
- Index.html
 - styles.css
 - updated README.md
 - git ignore file was also added and test.md file was ignored
 -

### CODE REVIEW

**Review by Donard97 — CHANGES_REQUESTED** [review]
## Hi @davidobi , 
    
Great work on the project! 👏 
You have one more step to do and you did it! 💯 💯 💯 
    
### Required Changes ♻️

- [x] Kindly add node modules to gitignore file

## Optional suggestions
    
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
    
**Cheers and Happy coding!👏👏👏**
    
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.
    
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
    
-------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by davidobi** [comment]
@Donard97 Thanks for the feedback. I have added the node_modules. Please review

**Comment by Donard97** [comment]
> @Donard97 Thanks for the feedback. I have added the node_modules. Please review

@davidobi Good job now submit it! 👏

**Review by alexander16108 — APPROVED** [review]
Hi @davidobi, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 😄 

> good job communicating with the code reviewer when  you have troubles, its a sign of a good developer 👍🏾 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
